Fix hardcode path
linuxdeepin/dde-calendar pull request #49
Opened 2021-10-28 05:57 UTC by hillwoodroc

2022-07-11 05:27 UTC, BLumia requested changes

2022-07-11 05:27 UTC, BLumia commented on schedule-plugin/CMakeLists.txt
> +install(TARGETS ${PROJECT_NAME} DESTINATION ${LIB_INSTALL_DIR}/deepin-aiassistant/serivce-plugins)
`${LIB_INSTALL_DIR}` 并没有预先定义，应该用 `${CMAKE_INSTALL_LIBDIR}` 会更好点吧？

2022-09-13 08:51 UTC, wineee commented on schedule-plugin/CMakeLists.txt
> +install(TARGETS ${PROJECT_NAME} DESTINATION ${LIB_INSTALL_DIR}/deepin-aiassistant/serivce-plugins)
这里也应该是 https://github.com/linuxdeepin/developer-center/issues/3402 的一部分

直接使用 CMAKE_INSTALL_LIBDIR 在 debian 上会装到 /usr/lib/x86_64-linux-gnu

2023-02-21 07:36 UTC, myml commented
已合并

2023-02-21 07:36 UTC, closed without merging